 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default 
    
     steps:
       - checkout
       - run: dotnet restore ./aspnet-core/AutomaticAcceptanceTest.sln
       - run: dotnet build ./aspnet-core/AutomaticAcceptanceTest.sln
       - run: dotnet test ./aspnet-core/AutomaticAcceptanceTest.sln

       - run: docker login cicdprototyperegistry.azurecr.io --username cicdprototyperegistry --password $ACR_PW
       - run: docker build aspnet-core -t cicdprototyperegistry.azurecr.io/cicdprototyperegistry/cicdprototype:$CIRCLE_BUILD_NUM
       - run: docker push cicdprototyperegistry.azurecr.io/cicdprototyperegistry/cicdprototype:$CIRCLE_BUILD_NUM