 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: 
       name: win/default 
       shell: bash.exe
     environment:
       ACR_PW: $ACR_PW

     steps:
       - checkout
      #  - run: dotnet restore ./aspnet-core/AutomaticAcceptanceTest.sln
      #  - run: dotnet build ./aspnet-core/AutomaticAcceptanceTest.sln
      #  - run: dotnet test ./aspnet-core/AutomaticAcceptanceTest.sln
       - run: export ACR_PW=$ACR_PW && echo "$ACR_PW" | docker login cicdprototyperegistry.azurecr.io --username cicdprototyperegistry --password-stdin
       - run: docker build aspnet-core -t cicdprototyperegistry.azurecr.io/cicdprototyperegistry/cicdprototype:$CIRCLE_BUILD_NUM
       - run: docker push cicdprototyperegistry.azurecr.io/cicdprototyperegistry/cicdprototype:$CIRCLE_BUILD_NUM